export const files: string[] = [
  'Accents.app',
  'Alfred 4.app',
  'Amphetamine Enhancer.app',
  'Amphetamine.app',
  'Android File Transfer.app',
  'AnyDesk.app',
  'Audacity.app',
  'Authy Desktop.app',
  'Autoclick.app',
  'Badlion Client.app',
  'Bear.app',
  'Bitwarden.app',
  'Brave Browser.app',
  'Brother',
  'Brother iPrint&Scan.app',
  'Bumpr.app',
  'Camera Settings.app',
  'CheatSheet.app',
  'CurseForge.app',
  'Discord Canary.app',
  'Disk Inventory X.app',
  'Docker.app',
  'Electron Fiddle.app',
  'Exodus.app',
  'F3XSwift.app',
  'Figma.app',
  'Firefox.app',
  'GDLauncher.app',
  'GitHub Desktop.app',
  'GoodNotes.app',
  'HuionDriver',
  'Hyper.app',
  'ImageOptim.app',
  'Insomnia.app',
  'JW Library.app',
  'JetBrains Toolbox.app',
  'Keka.app',
  'Keynote.app',
  'KiCad',
  'Loopback.app',
  'MICROCRAFT.app',
  'MacPorts',
  'Macs Fan Control.app',
  'Meeter.app',
  'Minecraft.app',
  'Mingo.app',
  'MultiMC.app',
  'Notion.app',
  'Numbers.app',
  'OBS.app',
  'Obsidian.app',
  'OnyX.app',
  'Opera GX.app',
  'Pages.app',
  'Pictogram.app',
  'ProtonVPN.app',
  'RealVNC',
  'Rectangle.app',
  'Rocket.app',
  'Safari.app',
  'Scroll Reverser.app',
  'Sizzy.app',
  'Spark.app',
  'Speedtest.app',
  'Spotify.app',
  'Steam.app',
  'Streamlabs OBS.app',
  'TechnicLauncher.jar',
  'Typora.app',
  'UTM.app',
  'Unity',
  'Utilities',
  'VLC.app',
  'VNC Viewer.app',
  'Vanilla.app',
  'Vectornator.app',
  'Visual Studio Code.app',
  'Vivaldi.app',
  'WhatsApp.app',
  'Xcode.app',
  'balenaEtcher.app',
  'dockey.app',
  'iMazing.app',
  'iTerm2.app',
  'osu!.app',
  'zoom.us.app'
];
